PACKAGE_NAME="tbs5930"
PACKAGE_VERSION="1.1"
AUTOINSTALL="yes"

MAKE[0]="make -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build/drivers/media CONFIG_MEDIA_SUPPORT=m CONFIG_DVB_CORE=m CONFIG_DVB_NET=y CONFIG_DVB_USB_TBS5930=m CONFIG_DVB_M88RS6060=m modules"
CLEAN="make -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build/drivers/media clean"

BUILT_MODULE_NAME[0]="dvb-usb-tbs5930"
BUILT_MODULE_LOCATION[0]="drivers/media/usb/dvb-usb-v2/"
DEST_MODULE_LOCATION[0]="/updates/dkms/"

BUILT_MODULE_NAME[1]="m88rs6060"
BUILT_MODULE_LOCATION[1]="drivers/media/dvb-frontends/"
DEST_MODULE_LOCATION[1]="/updates/dkms/"
